### ISSUE TITLE
Relative recursive patterns should be rewritten using **

### ISSUE THREAD

**Issue by aomarks** [foray1010/ignore-sync#302]
Per https://git-scm.com/docs/gitignore#_pattern_format, if you have a `.gitignore` pattern that does not contain a slash at the start or in the middle, then it matches recursively in any sub-directory relative the `.gitignore` dirname:

Examples:

- `foo.js` matches `./foo.js` and `./bar/foo.js`
- `foo/` matches `./foo/` and `./bar/foo/`
- `/foo.js` only matches `./foo.js`
- `foo/bar.js` only matches `./foo/bar.js`

However, currently when using the `[relative]` tag, globs are rewritten simply by prepending the dirname of the `.gitignore`, e.g.:

- `foo.js` becomes <strike>`relative/path/foo.js`</strike>

This is incorrect, because it converts recursive patterns into non-recursive ones. I think patterns without a slash at the start or middle should instead be re-written using a `**`:

- `foo.js` becomes `relative/path/**/foo.js`
- `foo/` becomes `relative/path/**/foo/`
- `/foo.js` becomes `relative/path/foo.js`
- `foo/bar.js` becomes `relative/path/foo/bar.js`

**Comment by foray1010** [comment]
fixed in [3.0.1](https://github.com/foray1010/ignore-sync/blob/master/CHANGELOG.md#301-2020-11-16)🎉
