### ISSUE TITLE
Allow referencing ignore-sync files from within a ignore-sync file

### ISSUE THREAD

**Issue by amithgeorge** [foray1010/ignore-sync#597]
My use case is to generate a `.prettierignore` from a `.gitignore` with some additional data. This works perfectly. 

```
[local]
.gitignore

[inline]
package-lock.json
```

However I would like to take it one step ahead, where my `.gitignore` is also generated by ignore-sync. I tried, 

```
[local]
.gitignore-sync

[inline]
package-lock.json
```

but the above generates an invalid file 

```
############################################
# GENERATED BY IGNORE-SYNC, DO NOT EDIT!!! #
# https://github.com/foray1010/ignore-sync #
############################################

[inline]
client/dist

[github/gitignore]
Node.gitignore
Global/macOS.gitignore

package-lock.json
```

For context, my `.gitignore-sync` is

```
[inline]
client/dist

[github/gitignore]
Node.gitignore
Global/macOS.gitignore


```

**Comment by foray1010** [comment]
Very nice idea! I have implemented it in v6 🥳

**Comment by amithgeorge** [comment]
Used v6.0.1. The features works great! Thank you so much for the prompt response and updates.
