### ISSUE TITLE
Add support for referencing a specific branch

### ISSUE THREAD

**Issue by risu729** [foray1010/ignore-sync#680]
Currently, all GitHub sources are retrieved from the master branch.

I want to use the reference to other commits, branches, and tags.

e.g. `[github/gitignore#main]`

If this feature is okay to add, I will send a PR.

**Comment by foray1010** [comment]
I think there are two improvements we can do:
1. Get the correct default branch name by https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository , I think it is a critical bug fix.
2. New syntax `[github/gitignore#main]` like you proposed

It will be great if you could send a PR either way!

**Comment by risu729** [comment]
Thank you for your information.

I will work on both two!
